---

- name: Main Playbook
  gather_facts: false
  hosts: all
  become: true
  roles:

    - role: tools
      tags: tools

    - role: jen_master
      tags: jen_master

    - role: jen_slave
      tags: jen_slave
