--- 
- name: Include variables
  include_vars: "../../../inventory/vars.yml"

- name: Create volumes where jenkins stores data
  containers.podman.podman_volume:
    name: jenkins_data
    state: present

- name: create dir to store certs
  file:
    path: "{{jenkins_cert}}"
    state: directory
    recurse: true
    mode: '0755'

## copia certificati
- name: Copy certificates
  copy:
    src: "../file/"
    dest: "{{jenkins_cert}}"
    remote_src: false

- name: Pull latest jenkins image
  containers.podman.podman_image:
    name: docker.io/jenkins/jenkins
    state: present

- name: Start jenkins container
  containers.podman.podman_container:
    name: jenkins_master
    image: docker.io/jenkins/jenkins
    state: started
    restart_policy: always
    cap_add:
      - NET_RAW
    volumes:
      - "jenkins_data:/var/jenkins_home:z"
      - "{{jenkins_cert}}/certificate.crt:/etc/ssl/certs/certificate.crt:z"
      - "{{jenkins_cert}}/privateKey.key:/etc/ssl/private/privateKey.key:z"
      - "{{jenkins_cert}}/certificate_new.p12:/etc/ssl/certs/certificate_new.p12:z"
    network: podman_internal
    ip: 192.168.100.2
    ports:
      - "8080:8080"
      - "5000:5000"
      - "8443:8443"
    command:
 #     --httpsPort=8443
 #     --httpsKeyStore=/etc/ssl/certs/certificate_new.p12
 #     --httpsKeyStorePassword=password


- name: Take Pass
  containers.podman.podman_container_exec:
    name: jenkins_master
    command: /bin/bash -c "cat /var/jenkins_home/secrets/initialAdminPassword"
  register: pass_admin

- name: debug
  debug:
    var: pass_admin 

- name: Download cli.jar
  get_url:
    url: http://192.168.100.2:8080/jnlpJars/jenkins-cli.jar
    dest: /home/vagrant/



# - name: export token variable
#   shell:
#     cmd: export JENKINS_API_TOKEN="{{token}}"
#   args:
#     executable: /bin/bash

# - name: export user variable
#   shell:
#     cmd: export JENKINS_USER_ID="{{user}}"
#   args:  
#       executable: /bin/bash

# - name: export url jenkins variable
#   shell:
#     cmd: export JENKINS_URL="{{url_jenkins}}"
#   args:
#       executable: /bin/bash